export type ElementCategory =
  | 'alkali'
  | 'alkaline'
  | 'transition'
  | 'post-transition'
  | 'metalloid'
  | 'nonmetal'
  | 'halogen'
  | 'noble'
  | 'lanthanide'
  | 'actinide';

export interface PeriodicElement {
  z: number;
  symbol: string;
  mass: number | string;
  /** 1–18 для основной сетки; 0 для лантаноидов/актиноидов в отдельных рядах */
  group: number;
  /** 1–7 для основной сетки; 8 — лантаноиды, 9 — актиноиды */
  period: number;
  name: { ru: string; kz: string };
  category: ElementCategory;
}

export const periodicElements: PeriodicElement[] = [
  { z: 1, symbol: 'H', mass: 1.008, group: 1, period: 1, name: { ru: 'Водород', kz: 'Сутек' }, category: 'nonmetal' },
  { z: 2, symbol: 'He', mass: 4.0026, group: 18, period: 1, name: { ru: 'Гелий', kz: 'Гелий' }, category: 'noble' },
  { z: 3, symbol: 'Li', mass: 6.94, group: 1, period: 2, name: { ru: 'Литий', kz: 'Литий' }, category: 'alkali' },
  { z: 4, symbol: 'Be', mass: 9.0122, group: 2, period: 2, name: { ru: 'Бериллий', kz: 'Бериллий' }, category: 'alkaline' },
  { z: 5, symbol: 'B', mass: 10.81, group: 13, period: 2, name: { ru: 'Бор', kz: 'Бор' }, category: 'metalloid' },
  { z: 6, symbol: 'C', mass: 12.011, group: 14, period: 2, name: { ru: 'Углерод', kz: 'Көміртек' }, category: 'nonmetal' },
  { z: 7, symbol: 'N', mass: 14.007, group: 15, period: 2, name: { ru: 'Азот', kz: 'Азот' }, category: 'nonmetal' },
  { z: 8, symbol: 'O', mass: 15.999, group: 16, period: 2, name: { ru: 'Кислород', kz: 'Оттегі' }, category: 'nonmetal' },
  { z: 9, symbol: 'F', mass: 18.998, group: 17, period: 2, name: { ru: 'Фтор', kz: 'Фтор' }, category: 'halogen' },
  { z: 10, symbol: 'Ne', mass: 20.18, group: 18, period: 2, name: { ru: 'Неон', kz: 'Неон' }, category: 'noble' },
  { z: 11, symbol: 'Na', mass: 22.99, group: 1, period: 3, name: { ru: 'Натрий', kz: 'Натрий' }, category: 'alkali' },
  { z: 12, symbol: 'Mg', mass: 24.305, group: 2, period: 3, name: { ru: 'Магний', kz: 'Магний' }, category: 'alkaline' },
  { z: 13, symbol: 'Al', mass: 26.982, group: 13, period: 3, name: { ru: 'Алюминий', kz: 'Алюминий' }, category: 'post-transition' },
  { z: 14, symbol: 'Si', mass: 28.085, group: 14, period: 3, name: { ru: 'Кремний', kz: 'Кремний' }, category: 'metalloid' },
  { z: 15, symbol: 'P', mass: 30.974, group: 15, period: 3, name: { ru: 'Фосфор', kz: 'Фосфор' }, category: 'nonmetal' },
  { z: 16, symbol: 'S', mass: 32.06, group: 16, period: 3, name: { ru: 'Сера', kz: 'Күкірт' }, category: 'nonmetal' },
  { z: 17, symbol: 'Cl', mass: 35.45, group: 17, period: 3, name: { ru: 'Хлор', kz: 'Хлор' }, category: 'halogen' },
  { z: 18, symbol: 'Ar', mass: 39.948, group: 18, period: 3, name: { ru: 'Аргон', kz: 'Аргон' }, category: 'noble' },
  { z: 19, symbol: 'K', mass: 39.098, group: 1, period: 4, name: { ru: 'Калий', kz: 'Калий' }, category: 'alkali' },
  { z: 20, symbol: 'Ca', mass: 40.078, group: 2, period: 4, name: { ru: 'Кальций', kz: 'Кальций' }, category: 'alkaline' },
  { z: 21, symbol: 'Sc', mass: 44.956, group: 3, period: 4, name: { ru: 'Скандий', kz: 'Скандий' }, category: 'transition' },
  { z: 22, symbol: 'Ti', mass: 47.867, group: 4, period: 4, name: { ru: 'Титан', kz: 'Титан' }, category: 'transition' },
  { z: 23, symbol: 'V', mass: 50.942, group: 5, period: 4, name: { ru: 'Ванадий', kz: 'Ванадий' }, category: 'transition' },
  { z: 24, symbol: 'Cr', mass: 51.996, group: 6, period: 4, name: { ru: 'Хром', kz: 'Хром' }, category: 'transition' },
  { z: 25, symbol: 'Mn', mass: 54.938, group: 7, period: 4, name: { ru: 'Марганец', kz: 'Марганец' }, category: 'transition' },
  { z: 26, symbol: 'Fe', mass: 55.845, group: 8, period: 4, name: { ru: 'Железо', kz: 'Темір' }, category: 'transition' },
  { z: 27, symbol: 'Co', mass: 58.933, group: 9, period: 4, name: { ru: 'Кобальт', kz: 'Кобальт' }, category: 'transition' },
  { z: 28, symbol: 'Ni', mass: 58.693, group: 10, period: 4, name: { ru: 'Никель', kz: 'Никель' }, category: 'transition' },
  { z: 29, symbol: 'Cu', mass: 63.546, group: 11, period: 4, name: { ru: 'Медь', kz: 'Мыс' }, category: 'transition' },
  { z: 30, symbol: 'Zn', mass: 65.38, group: 12, period: 4, name: { ru: 'Цинк', kz: 'Цинк' }, category: 'transition' },
  { z: 31, symbol: 'Ga', mass: 69.723, group: 13, period: 4, name: { ru: 'Галлий', kz: 'Галлий' }, category: 'post-transition' },
  { z: 32, symbol: 'Ge', mass: 72.63, group: 14, period: 4, name: { ru: 'Германий', kz: 'Германий' }, category: 'metalloid' },
  { z: 33, symbol: 'As', mass: 74.922, group: 15, period: 4, name: { ru: 'Мышьяк', kz: 'Күшән' }, category: 'metalloid' },
  { z: 34, symbol: 'Se', mass: 78.971, group: 16, period: 4, name: { ru: 'Селен', kz: 'Селен' }, category: 'nonmetal' },
  { z: 35, symbol: 'Br', mass: 79.904, group: 17, period: 4, name: { ru: 'Бром', kz: 'Бром' }, category: 'halogen' },
  { z: 36, symbol: 'Kr', mass: 83.798, group: 18, period: 4, name: { ru: 'Криптон', kz: 'Криптон' }, category: 'noble' },
  { z: 37, symbol: 'Rb', mass: 85.468, group: 1, period: 5, name: { ru: 'Рубидий', kz: 'Рубидий' }, category: 'alkali' },
  { z: 38, symbol: 'Sr', mass: 87.62, group: 2, period: 5, name: { ru: 'Стронций', kz: 'Стронций' }, category: 'alkaline' },
  { z: 39, symbol: 'Y', mass: 88.906, group: 3, period: 5, name: { ru: 'Иттрий', kz: 'Иттрий' }, category: 'transition' },
  { z: 40, symbol: 'Zr', mass: 91.224, group: 4, period: 5, name: { ru: 'Цирконий', kz: 'Цирконий' }, category: 'transition' },
  { z: 41, symbol: 'Nb', mass: 92.906, group: 5, period: 5, name: { ru: 'Ниобий', kz: 'Ниобий' }, category: 'transition' },
  { z: 42, symbol: 'Mo', mass: 95.95, group: 6, period: 5, name: { ru: 'Молибден', kz: 'Молибден' }, category: 'transition' },
  { z: 43, symbol: 'Tc', mass: '[98]', group: 7, period: 5, name: { ru: 'Технеций', kz: 'Технеций' }, category: 'transition' },
  { z: 44, symbol: 'Ru', mass: 101.07, group: 8, period: 5, name: { ru: 'Рутений', kz: 'Рутений' }, category: 'transition' },
  { z: 45, symbol: 'Rh', mass: 102.91, group: 9, period: 5, name: { ru: 'Родий', kz: 'Родий' }, category: 'transition' },
  { z: 46, symbol: 'Pd', mass: 106.42, group: 10, period: 5, name: { ru: 'Палладий', kz: 'Палладий' }, category: 'transition' },
  { z: 47, symbol: 'Ag', mass: 107.87, group: 11, period: 5, name: { ru: 'Серебро', kz: 'Күміс' }, category: 'transition' },
  { z: 48, symbol: 'Cd', mass: 112.41, group: 12, period: 5, name: { ru: 'Кадмий', kz: 'Кадмий' }, category: 'transition' },
  { z: 49, symbol: 'In', mass: 114.82, group: 13, period: 5, name: { ru: 'Индий', kz: 'Индий' }, category: 'post-transition' },
  { z: 50, symbol: 'Sn', mass: 118.71, group: 14, period: 5, name: { ru: 'Олово', kz: 'Қалайы' }, category: 'post-transition' },
  { z: 51, symbol: 'Sb', mass: 121.76, group: 15, period: 5, name: { ru: 'Сурьма', kz: 'Сүрме' }, category: 'metalloid' },
  { z: 52, symbol: 'Te', mass: 127.6, group: 16, period: 5, name: { ru: 'Теллур', kz: 'Теллур' }, category: 'metalloid' },
  { z: 53, symbol: 'I', mass: 126.9, group: 17, period: 5, name: { ru: 'Йод', kz: 'Йод' }, category: 'halogen' },
  { z: 54, symbol: 'Xe', mass: 131.29, group: 18, period: 5, name: { ru: 'Ксенон', kz: 'Ксенон' }, category: 'noble' },
  { z: 55, symbol: 'Cs', mass: 132.91, group: 1, period: 6, name: { ru: 'Цезий', kz: 'Цезий' }, category: 'alkali' },
  { z: 56, symbol: 'Ba', mass: 137.33, group: 2, period: 6, name: { ru: 'Барий', kz: 'Барий' }, category: 'alkaline' },
  { z: 57, symbol: 'La', mass: 138.91, group: 3, period: 6, name: { ru: 'Лантан', kz: 'Лантан' }, category: 'lanthanide' },
  { z: 58, symbol: 'Ce', mass: 140.12, group: 0, period: 8, name: { ru: 'Церий', kz: 'Церий' }, category: 'lanthanide' },
  { z: 59, symbol: 'Pr', mass: 140.91, group: 0, period: 8, name: { ru: 'Празеодим', kz: 'Празеодим' }, category: 'lanthanide' },
  { z: 60, symbol: 'Nd', mass: 144.24, group: 0, period: 8, name: { ru: 'Неодим', kz: 'Неодим' }, category: 'lanthanide' },
  { z: 61, symbol: 'Pm', mass: '[145]', group: 0, period: 8, name: { ru: 'Прометий', kz: 'Прометий' }, category: 'lanthanide' },
  { z: 62, symbol: 'Sm', mass: 150.36, group: 0, period: 8, name: { ru: 'Самарий', kz: 'Самарий' }, category: 'lanthanide' },
  { z: 63, symbol: 'Eu', mass: 151.96, group: 0, period: 8, name: { ru: 'Европий', kz: 'Европий' }, category: 'lanthanide' },
  { z: 64, symbol: 'Gd', mass: 157.25, group: 0, period: 8, name: { ru: 'Гадолиний', kz: 'Гадолиний' }, category: 'lanthanide' },
  { z: 65, symbol: 'Tb', mass: 158.93, group: 0, period: 8, name: { ru: 'Тербий', kz: 'Тербий' }, category: 'lanthanide' },
  { z: 66, symbol: 'Dy', mass: 162.5, group: 0, period: 8, name: { ru: 'Диспрозий', kz: 'Диспрозий' }, category: 'lanthanide' },
  { z: 67, symbol: 'Ho', mass: 164.93, group: 0, period: 8, name: { ru: 'Гольмий', kz: 'Гольмий' }, category: 'lanthanide' },
  { z: 68, symbol: 'Er', mass: 167.26, group: 0, period: 8, name: { ru: 'Эрбий', kz: 'Эрбий' }, category: 'lanthanide' },
  { z: 69, symbol: 'Tm', mass: 168.93, group: 0, period: 8, name: { ru: 'Тулий', kz: 'Тулий' }, category: 'lanthanide' },
  { z: 70, symbol: 'Yb', mass: 173.05, group: 0, period: 8, name: { ru: 'Иттербий', kz: 'Иттербий' }, category: 'lanthanide' },
  { z: 71, symbol: 'Lu', mass: 174.97, group: 0, period: 8, name: { ru: 'Лютеций', kz: 'Лютеций' }, category: 'lanthanide' },
  { z: 72, symbol: 'Hf', mass: 178.49, group: 4, period: 6, name: { ru: 'Гафний', kz: 'Гафний' }, category: 'transition' },
  { z: 73, symbol: 'Ta', mass: 180.95, group: 5, period: 6, name: { ru: 'Тантал', kz: 'Тантал' }, category: 'transition' },
  { z: 74, symbol: 'W', mass: 183.84, group: 6, period: 6, name: { ru: 'Вольфрам', kz: 'Вольфрам' }, category: 'transition' },
  { z: 75, symbol: 'Re', mass: 186.21, group: 7, period: 6, name: { ru: 'Рений', kz: 'Рений' }, category: 'transition' },
  { z: 76, symbol: 'Os', mass: 190.23, group: 8, period: 6, name: { ru: 'Осмий', kz: 'Осмий' }, category: 'transition' },
  { z: 77, symbol: 'Ir', mass: 192.22, group: 9, period: 6, name: { ru: 'Иридий', kz: 'Иридий' }, category: 'transition' },
  { z: 78, symbol: 'Pt', mass: 195.08, group: 10, period: 6, name: { ru: 'Платина', kz: 'Платина' }, category: 'transition' },
  { z: 79, symbol: 'Au', mass: 196.97, group: 11, period: 6, name: { ru: 'Золото', kz: 'Алтын' }, category: 'transition' },
  { z: 80, symbol: 'Hg', mass: 200.59, group: 12, period: 6, name: { ru: 'Ртуть', kz: 'Сынап' }, category: 'post-transition' },
  { z: 81, symbol: 'Tl', mass: 204.38, group: 13, period: 6, name: { ru: 'Таллий', kz: 'Таллий' }, category: 'post-transition' },
  { z: 82, symbol: 'Pb', mass: 207.2, group: 14, period: 6, name: { ru: 'Свинец', kz: 'Қорғасын' }, category: 'post-transition' },
  { z: 83, symbol: 'Bi', mass: 208.98, group: 15, period: 6, name: { ru: 'Висмут', kz: 'Висмут' }, category: 'post-transition' },
  { z: 84, symbol: 'Po', mass: '[209]', group: 16, period: 6, name: { ru: 'Полоний', kz: 'Полоний' }, category: 'metalloid' },
  { z: 85, symbol: 'At', mass: '[210]', group: 17, period: 6, name: { ru: 'Астат', kz: 'Астат' }, category: 'halogen' },
  { z: 86, symbol: 'Rn', mass: '[222]', group: 18, period: 6, name: { ru: 'Радон', kz: 'Радон' }, category: 'noble' },
  { z: 87, symbol: 'Fr', mass: '[223]', group: 1, period: 7, name: { ru: 'Франций', kz: 'Франций' }, category: 'alkali' },
  { z: 88, symbol: 'Ra', mass: '[226]', group: 2, period: 7, name: { ru: 'Радий', kz: 'Радий' }, category: 'alkaline' },
  { z: 89, symbol: 'Ac', mass: '[227]', group: 3, period: 7, name: { ru: 'Актиний', kz: 'Актиний' }, category: 'actinide' },
  { z: 90, symbol: 'Th', mass: 232.04, group: 0, period: 9, name: { ru: 'Торий', kz: 'Торий' }, category: 'actinide' },
  { z: 91, symbol: 'Pa', mass: 231.04, group: 0, period: 9, name: { ru: 'Протактиний', kz: 'Протактиний' }, category: 'actinide' },
  { z: 92, symbol: 'U', mass: 238.03, group: 0, period: 9, name: { ru: 'Уран', kz: 'Уран' }, category: 'actinide' },
  { z: 93, symbol: 'Np', mass: '[237]', group: 0, period: 9, name: { ru: 'Нептуний', kz: 'Нептуний' }, category: 'actinide' },
  { z: 94, symbol: 'Pu', mass: '[244]', group: 0, period: 9, name: { ru: 'Плутоний', kz: 'Плутоний' }, category: 'actinide' },
  { z: 95, symbol: 'Am', mass: '[243]', group: 0, period: 9, name: { ru: 'Америций', kz: 'Америций' }, category: 'actinide' },
  { z: 96, symbol: 'Cm', mass: '[247]', group: 0, period: 9, name: { ru: 'Кюрий', kz: 'Кюрий' }, category: 'actinide' },
  { z: 97, symbol: 'Bk', mass: '[247]', group: 0, period: 9, name: { ru: 'Берклий', kz: 'Берклий' }, category: 'actinide' },
  { z: 98, symbol: 'Cf', mass: '[251]', group: 0, period: 9, name: { ru: 'Калифорний', kz: 'Калифорний' }, category: 'actinide' },
  { z: 99, symbol: 'Es', mass: '[252]', group: 0, period: 9, name: { ru: 'Эйнштейний', kz: 'Эйнштейний' }, category: 'actinide' },
  { z: 100, symbol: 'Fm', mass: '[257]', group: 0, period: 9, name: { ru: 'Фермий', kz: 'Фермий' }, category: 'actinide' },
  { z: 101, symbol: 'Md', mass: '[258]', group: 0, period: 9, name: { ru: 'Менделевий', kz: 'Менделевий' }, category: 'actinide' },
  { z: 102, symbol: 'No', mass: '[259]', group: 0, period: 9, name: { ru: 'Нобелий', kz: 'Нобелий' }, category: 'actinide' },
  { z: 103, symbol: 'Lr', mass: '[266]', group: 0, period: 9, name: { ru: 'Лоуренсий', kz: 'Лоуренсий' }, category: 'actinide' },
  { z: 104, symbol: 'Rf', mass: '[267]', group: 4, period: 7, name: { ru: 'Резерфордий', kz: 'Резерфордий' }, category: 'transition' },
  { z: 105, symbol: 'Db', mass: '[268]', group: 5, period: 7, name: { ru: 'Дубний', kz: 'Дубний' }, category: 'transition' },
  { z: 106, symbol: 'Sg', mass: '[269]', group: 6, period: 7, name: { ru: 'Сиборгий', kz: 'Сиборгий' }, category: 'transition' },
  { z: 107, symbol: 'Bh', mass: '[270]', group: 7, period: 7, name: { ru: 'Борий', kz: 'Борий' }, category: 'transition' },
  { z: 108, symbol: 'Hs', mass: '[277]', group: 8, period: 7, name: { ru: 'Хассий', kz: 'Хассий' }, category: 'transition' },
  { z: 109, symbol: 'Mt', mass: '[278]', group: 9, period: 7, name: { ru: 'Мейтнерий', kz: 'Мейтнерий' }, category: 'transition' },
  { z: 110, symbol: 'Ds', mass: '[281]', group: 10, period: 7, name: { ru: 'Дармштадтий', kz: 'Дармштадтий' }, category: 'transition' },
  { z: 111, symbol: 'Rg', mass: '[282]', group: 11, period: 7, name: { ru: 'Рентгений', kz: 'Рентгений' }, category: 'transition' },
  { z: 112, symbol: 'Cn', mass: '[285]', group: 12, period: 7, name: { ru: 'Коперниций', kz: 'Коперниций' }, category: 'transition' },
  { z: 113, symbol: 'Nh', mass: '[286]', group: 13, period: 7, name: { ru: 'Нихоний', kz: 'Нихоний' }, category: 'post-transition' },
  { z: 114, symbol: 'Fl', mass: '[289]', group: 14, period: 7, name: { ru: 'Флеровий', kz: 'Флеровий' }, category: 'post-transition' },
  { z: 115, symbol: 'Mc', mass: '[290]', group: 15, period: 7, name: { ru: 'Московий', kz: 'Московий' }, category: 'post-transition' },
  { z: 116, symbol: 'Lv', mass: '[293]', group: 16, period: 7, name: { ru: 'Ливерморий', kz: 'Ливерморий' }, category: 'post-transition' },
  { z: 117, symbol: 'Ts', mass: '[294]', group: 17, period: 7, name: { ru: 'Теннессин', kz: 'Теннессин' }, category: 'halogen' },
  { z: 118, symbol: 'Og', mass: '[294]', group: 18, period: 7, name: { ru: 'Оганесон', kz: 'Оганесон' }, category: 'noble' },
];
